// src/components/Projects.tsx
import { FC } from 'react'

const projects = [
  {
    title: 'Mealpractice: Build your practice and share it with the world!',
    url: 'https://www.mealpractice.com',
    image: 'https://cdn.mealpractice.com/logo.svg',
    body: 'Mealpractice makes it easy to cook and share the recipes you love. Discover new recipes by following practitioners with similar tastes or nutritional goals.',
  },
  {
    title: 'Astrify: Create custom stellar.toml files in seconds!',
    url: 'https://astrify.com',
    image: 'https://raw.githubusercontent.com/benbjurstrom/prezet/main/art/logo.png',
    body: "Astrify makes it easy to publish assets on the stellar network. Add your organization's information to a custom stellar.toml file. Accounts, assets, validators, and principals that are linked to the organization will show up in real time.",
  },
  {
    title: 'Prezet: Markdown Blogging for Laravel',
    url: 'https://prezet.com',
    image: 'https://s3-us-west-2.amazonaws.com/benbjurstrom.com/img/projects/prezet.png',
    body: 'Transform your markdown files into SEO-friendly blogs, articles, and documentation!',
  },
  {
    title: 'Webconcepts Youtube Channel',
    url: 'https://www.youtube.com/c/webconcepts',
    image: 'https://s3-us-west-2.amazonaws.com/benbjurstrom.com/img/projects/web-concepts.png',
    body: 'A youtube channel covering various concepts related to web development. My goal with this channel is to provide quick overviews and examples to bring awareness to the topic.',
  },
  {
    title: 'Personal Youtube Channel',
    url: 'https://www.youtube.com/c/benbjurstrom',
    image: 'https://s3-us-west-2.amazonaws.com/benbjurstrom.com/img/projects/benbjurstrom.png',
    body: 'A youtube channel with videos about cameras, tech, and whatever else catches my interest.',
  },
]

const Projects: FC = (): JSX.Element => {
  return (
    <>
      {projects.map((project) => (
        <a
          href={project.url}
          key={project.title}
          target="_blank"
          rel="noreferrer"
          className="hover:border-gray block px-4 py-6 hover:text-black hover:bg-gray-200 border-b border-t border-transparent"
        >
          <div className="md:flex">
            <div className="flex-shrink-0 mb-4 sm:mb-0 sm:mr-4">
              <img className="w-36 h-36 md:w-48 md:h-48" src={project.image} alt="" />
            </div>
            <div>
              <div className="mt-4 text-gray-800 font-serif text-lg font-semibold md:mt-0">{project.title}</div>
              <p className="mt-1">{project.body}</p>
            </div>
          </div>
        </a>
      ))}
    </>
  )
}

export default Projects

// .vuepress/theme/pages/Projects.vue
<template>
    <div>
        <h1 class="my-8 mx-6">Projects</h1>
        <a href="https://astrify.com" target="_blank" class="block py-6 hover:bg-gray-200 border-b border-t border-transparent hover:border-gray hover:text-black">
            <div class="flex">
                <div class="w-1/3">
                    <div class="relative pb-2/3 text-blue-800">
                        <svg viewBox="0 0 270 270" xmlns="http://www.w3.org/2000/svg" class="absolute top-0 h-full w-full object-cover fill-current">
                            <path d="M161.181 16.875l104.724 202.5c11.636 22.5-2.909 50.625-26.181 50.625H195c-34.887 0-34.275-23.819-34.887-37.447-.099-2.207 1.678-3.995 3.887-3.995h27.493c.833 0 1.507-.67 1.507-1.498v-9.168c0-.365-.134-.717-.377-.991l-23.727-25.036c9.353-34.806-5.245-66.142-33.896-86.865-28.841 20.422-43.249 52.059-33.896 86.865l-23.727 25.036a1.493 1.493 0 0 0-.377.991v9.168c0 .828.674 1.498 1.507 1.498H106c2.209 0 3.986 1.788 3.887 3.995-.612 13.628 0 37.447-34.887 37.447H30.276c-23.272 0-37.817-28.125-26.18-50.625l104.723-202.5c11.636-22.5 40.726-22.5 52.362 0z">
                            </path>
                            <path fill-rule="evenodd" d="M135 179.884c10.331 0 18.831-8.423 18.831-18.721s-8.5-18.721-18.831-18.721-18.831 8.423-18.831 18.721 8.5 18.721 18.831 18.721zm-2.871-32.765c.032 1.094.916 1.998 2.021 1.998 2.036-.016 3.978.443 5.683 1.315 1.783.872 3.314 2.173 4.514 3.758a1.98 1.98 0 0 0 2.778.397c.869-.651 1.042-1.919.395-2.791a16.486 16.486 0 0 0-5.919-4.963c-2.258-1.109-4.799-1.76-7.483-1.744-1.089.032-1.989.92-1.989 2.03zm15.644 8.783c-1.058.286-1.674 1.396-1.39 2.458.158.523.253 1.094.332 1.665.079.539.11 1.11.11 1.712.032 1.094.916 2.014 2.021 1.998a2.023 2.023 0 0 0 1.989-2.03 17.924 17.924 0 0 0-.174-2.219 17.06 17.06 0 0 0-.442-2.188c-.284-1.063-1.389-1.681-2.446-1.396z" clip-rule="evenodd">
                            </path>
                        </svg>
                    </div>
                </div>
                <div class="w-2/3">
                    <div class="font-serif font-bold">Astrify.com</div>
                    <div class="text-sm">
                        Create custom stellar.toml files in seconds! Astrify makes it easy to publish assets on the stellar network. Astrify makes it easy for you to add your organization's information to a custom stellar.toml file. Accounts, assets, validators, and principals that are linked to the organization will show up in real time.
                    </div>
                </div>
            </div>
        </a>
    </div>
</template>

<script>
    export default {
        //
    }
</script>
