// .vuepress/theme/global-components/YouTube.vue
<template>
    <div class="bleed relative" style="padding-top: 56.25%;">
        <iframe
            :src="url" width="560" height="315"
            frameborder="0" allow="autoplay; encrypted-media" allowfullscreen
            class="inline"
        ></iframe>
    </div>
</template>

<script>
export default {
    props: {
        url: { required: true },
    }
}
</script>

<style lang="stylus" scoped>
iframe
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
</style>

// src/components/youtube.tsx
const PostBody = ({ url }: { url: string }): JSX.Element => {
  return (
    <div className="aspect-w-16 aspect-h-9">
      <iframe
        src={url}
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowFullScreen
      />
    </div>
  )
}

export default PostBody
